### ISSUE TITLE
Wrong URL for xfsettingsd

### ISSUE THREAD

**Issue by aakeene** [linuxmint/mintreport#100]
I am getting a crash dump for xfsettingsd that is reported in the "System Reports" application.  However,  clicking on the "Bug Tracker" button does not bring up a valid location for reporting the crash - the [website](https://github.com/linuxmint/xfce4-settings/issues) which is suggested is not a valid location (page not found).

It has been suggested in the linux mint forums that this [proposed website](https://docs.xfce.org/xfce/xfce4-settings/bugs) be used instead as the correct reporting URL, but I do not know myself if that is correct.

Link to linux forum discussion is [here](https://forums.linuxmint.com/viewtopic.php?t=411836).

**Comment by clefebvre** [comment]
Thanks @aakeene,

It's a bit of a special case but it's a good thing this led you here.

Although xfce4-settings isn't a package we maintain, it is provided by our repositories (we backport version 4.18 basically).

http://packages.linuxmint.com/search.php?release=any&section=any&keyword=xfce4-settings

mintreport tries to guess the first point of contact for the bug report, based on the origin of the package. Here it is Mint and not Ubuntu.

It could certainly be smarter about it, but as it is for now it works as it was designed.
