### ISSUE TITLE
Typical recommendation breaks system (gimp-help-en pulls wslu which destroys xdg-open)

### ISSUE THREAD

**Issue by SomeTroglodyte** [linuxmint/mintreport#104]
The very [screenshot in your readme](https://user-images.githubusercontent.com/19881231/122669008-e114d980-d1c3-11eb-928d-905684286545.png) shows a typical "install language packs" prompt urging a victim -e.g. shortly after a typical fresh install of Mint22- to install gimp-help-en.
Which depends on wslu.
Which somehow goads xdg-open to ignore mime types and call wslview for - most things??? Typical first noticeable symptom being Super-E breaks.

In that situation:
* Binding Super-E to a custom shortcut directly calling nemo will work around the perceived Super-E "bug".
* But other interactions still break - like opening a directory from a deluge torrent or certain open actions from Android Studio or or or...
* `xdg-open .` from the shell throws errors mentioning wslview - and blocks indefinitely.
* `wslview` from the shell throws most of the same errors, something about some library missing IIRC.
* `sudo apt purge wslu -y` fixes all problems except bringing the erroneous "system errors require your attention" back.

I would expect:
* Some missing help files shouldn't be treated as a system problem needing troubleshooting
* A plain help file shouldn't pull in buggy packages that can only work on FOSS-inimical platforms
* xdg-open should honor its configuration in all circumstances and not allow itself to be hijacked

**Comment by clefebvre** [comment]
gimp-help-en doesn't depend on wslu...

https://packages.ubuntu.com/noble/gimp-help-en
