### ISSUE TITLE
will mintreport work with Kubuntu if I compile from source?

### ISSUE THREAD

**Issue by MuhMuhGH** [linuxmint/mintreport#107]
I can't get mintreport via Discover Package Manager in Kubuntu.
Will mintreport work with Kubuntu if I compile from source?

I am running:

Operating System: Kubuntu 24.10
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.6.2
Kernel Version: 6.11.0-13-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 60.6 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: Framework
Product Name: Laptop 16 (AMD Ryzen 7040 Series)
System Version: AG

**Comment by mtwebster** [comment]
The system reports tool is intended only for Linux Mint, not Ubuntu or its derivatives. If it does work it may only be useful for things like looking at crash reports (though there may already be a tool in Kubuntu for this).

Feel free to try it though:
http://packages.linuxmint.com/search.php?release=xia&section=any&keyword=mintreport
