### ISSUE TITLE
Misspelling of occurred

### ISSUE THREAD

**Issue by to-ba** [linuxmint/mintreport#22]
https://github.com/linuxmint/mintreport/blob/master/mintreport.pot

Should it not be better »occurred«?

https://en.wiktionary.org/wiki/occured

**Comment by NoahGWood** [comment]
It should, that is the proper English. I fixed the spelling and sent a pull request, looks like it was merged. This issue should be closed.
PR: https://github.com/linuxmint/mintreport/pull/23

(Apologies, I forgot to reference the issue #)
