### ISSUE TITLE
issue with system reports Mint 19.1 - crash

### ISSUE THREAD

**Issue by pemergency** [linuxmint/mintreport#29]
===================================================================
 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 5689]
[New LWP 6111]
[New LWP 5692]
[New LWP 5694]
[New LWP 5693]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f830e476e97 in ?? ()
[Current thread is 1 (LWP 5689)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 5689]
[New LWP 6111]
[New LWP 5692]
[New LWP 5694]
[New LWP 5693]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f830e476e97 in ?? ()
[Current thread is 1 (LWP 5689)]
#0  0x00007f830e476e97 in ?? ()
#1  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 5689]
[New LWP 6111]
[New LWP 5692]
[New LWP 5694]
[New LWP 5693]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f830e476e97 in ?? ()
[Current thread is 1 (LWP 5689)]

Thread 5 (LWP 5693):
#0  0x00007f830e54cbf9 in ?? ()
No symbol table info available.
#1  0x00000000026121ac in ?? ()
No symbol table info available.
#2  0x000000000269f070 in ?? ()
No symbol table info available.
#3  0x0000000002612060 in ?? ()
No symbol table info available.
#4  0x0000000000000002 in ?? ()
No symbol table info available.
#5  0x000000000269f070 in ?? ()
No symbol table info available.
#6  0x00007f83092e14c9 in ?? ()
No symbol table info available.
#7  0x000000000269f060 in ?? ()
No symbol table info available.
#8  0x0000000102612060 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x01c653f3b99f4800 in ?? ()
No symbol table info available.
#11 0x000000000267bbe0 in ?? ()
No symbol table info available.
#12 0x00000000026121a0 in ?? ()
No symbol table info available.
#13 0x00000000026121ac in ?? ()
No symbol table info available.
#14 0x00007f82fbffefc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 5694):
#0  0x00007f830e54cbf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x0000000002784da0 in ?? ()
No symbol table info available.
#3  0x00000000028b2930 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x0000000002784da0 in ?? ()
No symbol table info available.
#6  0x00007f83092e14c9 in ?? ()
No symbol table info available.
#7  0x00007ffc4e6b7890 in ?? ()
No symbol table info available.
#8  0x00000001028b2930 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x01c653f3b99f4800 in ?? ()
No symbol table info available.
#11 0x00000000028b2930 in ?? ()
No symbol table info available.
#12 0x00000000028b2930 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007f82f8e5cfc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 5692):
#0  0x00007f830e54cbf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x000000000268bd80 in ?? ()
No symbol table info available.
#3  0x000000000268ba90 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x000000000268bd80 in ?? ()
No symbol table info available.
#6  0x00007f83092e14c9 in ?? ()
No symbol table info available.
#7  0x00007ffc4e6b71f0 in ?? ()
No symbol table info available.
#8  0x000000010e4cf2ed in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x01c653f3b99f4800 in ?? ()
No symbol table info available.
#11 0x000000000000002e in ?? ()
No symbol table info available.
#12 0x000000000268ba90 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007f8300c4efc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 6111):
#0  0x00000000005337b3 in ?? ()
No symbol table info available.
#1  0x00007f8309cc2c80 in ?? ()
No symbol table info available.
#2  0x00007f8307da56d8 in ?? ()
No symbol table info available.
#3  0x00007f8307df0b88 in ?? ()
No symbol table info available.
#4  0x00000000024d5dc8 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 5689):
#0  0x00007f830e476e97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007f830e476e97 in ?? ()
#1  0x0000000000000000 in ?? ()

**Comment by clefebvre** [comment]
Can you paste the output of "dpkg -l | grep mintreport"?

Try to reinstall it maybe...

**Comment by pemergency** [comment]
/usr/bin/mintreport: Python script, ASCII text executable
Linux pemergency-pc 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

mintreport crash when i try to view some of the report, for example this one
@ The file /var/crash/_usr_bin_gnome-shell.122.crash could not be read.
Please fix its permissions.@

sometimes it opens normally and next time freeze and close immediately.

**Comment by ioannis120** [comment]
i had the same issue twice i was running a window application Battlenet Blizzard and Firefox, I have Linux 4.15.0-55-generic x86_64
===================================================================
 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2496]
[New LWP 2500]
[New LWP 2499]
[New LWP 2709]
[New LWP 2501]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f671066ee97 in ?? ()
[Current thread is 1 (LWP 2496)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2496]
[New LWP 2500]
[New LWP 2499]
[New LWP 2709]
[New LWP 2501]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f671066ee97 in ?? ()
[Current thread is 1 (LWP 2496)]
#0  0x00007f671066ee97 in ?? ()
#1  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2496]
[New LWP 2500]
[New LWP 2499]
[New LWP 2709]
[New LWP 2501]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f671066ee97 in ?? ()
[Current thread is 1 (LWP 2496)]

Thread 5 (LWP 2501):
#0  0x00007f6710744bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000025b8b90 in ?? ()
No symbol table info available.
#3  0x0000000002469890 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000025b8b90 in ?? ()
No symbol table info available.
#6  0x00007f670b47c5c9 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 2709):
#0  0x00007f670b499ace in ?? ()
No symbol table info available.
#1  0x0000000000014670 in ?? ()
No symbol table info available.
#2  0x0000000000000004 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 2499):
#0  0x00007f6710744bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000023bdf80 in ?? ()
No symbol table info available.
#3  0x00000000023bdce0 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000023bdf80 in ?? ()
No symbol table info available.
#6  0x00007f670b47c5c9 in ?? ()
No symbol table info available.
#7  0x00007ffe49d493b0 in ?? ()
No symbol table info available.
#8  0x00000001106c72ed in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0xaa8b552c9f418e00 in ?? ()
No symbol table info available.
#11 0x000000000000002e in ?? ()
No symbol table info available.
#12 0x00000000023bdce0 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007f6702ad6fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 2500):
#0  0x00007f6710744bf9 in ?? ()
No symbol table info available.
#1  0x000000000233e52c in ?? ()
No symbol table info available.
#2  0x000000000232e660 in ?? ()
No symbol table info available.
#3  0x000000000233e3e0 in ?? ()
No symbol table info available.
#4  0x0000000000000002 in ?? ()
No symbol table info available.
#5  0x000000000232e660 in ?? ()
No symbol table info available.
#6  0x00007f670b47c5c9 in ?? ()
No symbol table info available.
#7  0x000000000232e650 in ?? ()
No symbol table info available.
#8  0x000000010233e3e0 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0xaa8b552c9f418e00 in ?? ()
No symbol table info available.
#11 0x00000000023b9df0 in ?? ()
No symbol table info available.
#12 0x000000000233e520 in ?? ()
No symbol table info available.
#13 0x000000000233e52c in ?? ()
No symbol table info available.
#14 0x00007f67022d5fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 2496):
#0  0x00007f671066ee97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007f671066ee97 in ?? ()
#1  0x0000000000000000 in ?? ()
 

 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 19460]
[New LWP 19464]
[New LWP 19484]
[New LWP 19465]
[New LWP 19463]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f90ea2eee97 in ?? ()
[Current thread is 1 (LWP 19460)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 19460]
[New LWP 19464]
[New LWP 19484]
[New LWP 19465]
[New LWP 19463]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f90ea2eee97 in ?? ()
[Current thread is 1 (LWP 19460)]
#0  0x00007f90ea2eee97 in ?? ()
#1  0x0000000000000000 in ?? ()


===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 19460]
[New LWP 19464]
[New LWP 19484]
[New LWP 19465]
[New LWP 19463]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f90ea2eee97 in ?? ()
[Current thread is 1 (LWP 19460)]

Thread 5 (LWP 19463):
#0  0x00007f90ea3c4bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000024b48a0 in ?? ()
No symbol table info available.
#3  0x00000000024b4600 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000024b48a0 in ?? ()
No symbol table info available.
#6  0x00007f90e50fc5c9 in ?? ()
No symbol table info available.
#7  0x00007ffcedb69140 in ?? ()
No symbol table info available.
#8  0x00000001ea3472ed in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x5c356e12cac83000 in ?? ()
No symbol table info available.
#11 0x000000000000002e in ?? ()
No symbol table info available.
#12 0x00000000024b4600 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007f90dc756fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 19465):
#0  0x00007f90ea3c4bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000026b2120 in ?? ()
No symbol table info available.
#3  0x000000000241f980 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000026b2120 in ?? ()
No symbol table info available.
#6  0x00007f90e50fc5c9 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 19484):
#0  0x00007f90e5119ad5 in ?? ()
No symbol table info available.
#1  0x0000000000014670 in ?? ()
No symbol table info available.
#2  0x0000000000000004 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 19464):
#0  0x00007f90ea3c4bf9 in ?? ()
No symbol table info available.
#1  0x000000000243460c in ?? ()
No symbol table info available.
#2  0x0000000002424db0 in ?? ()
No symbol table info available.
#3  0x00000000024344c0 in ?? ()
No symbol table info available.
#4  0x0000000000000002 in ?? ()
No symbol table info available.
#5  0x0000000002424db0 in ?? ()
No symbol table info available.
#6  0x00007f90e50fc5c9 in ?? ()
No symbol table info available.
#7  0x0000000002424da0 in ?? ()
No symbol table info available.
#8  0x00000001024344c0 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x5c356e12cac83000 in ?? ()
No symbol table info available.
#11 0x0000000002434c40 in ?? ()
No symbol table info available.
#12 0x0000000002434600 in ?? ()
No symbol table info available.
#13 0x000000000243460c in ?? ()
No symbol table info available.
#14 0x00007f90dbf55fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 19460):
#0  0x00007f90ea2eee97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007f90ea2eee97 in ?? ()
#1  0x0000000000000000 in ?? ()

**Comment by clefebvre** [comment]
I'm not sure how to solve this. That said, I don't think it will happen again in more recent versions of mintreport since we moved away from apport and switched to systemd-coredump.
