### ISSUE TITLE
Mint Report Crash

### ISSUE THREAD

**Issue by samarth-math** [linuxmint/mintreport#3]
Mint report crashes consistently when I tried to select a previous crash report.
https://gist.github.com/anonymous/5e8034c3e5dd17082a0fe76e7007b6e6
[crash.tar.gz](https://github.com/linuxmint/mintreport/files/1486195/crash.tar.gz)

**Comment by clefebvre** [comment]
What does dmesg say about this crash?

**Comment by samarth-math** [comment]
Interestingly dmesg doesn't say much.
I put it on watch, and as I launched mint report it printed this : 
[Nov22 14:27] audit: type=1400 audit(1511393275.605:34): apparmor="DENIED" operation="open" profile="/usr/sbin/ntpd" name="/run/expressvpn/resolv.conf" pid=1172 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=109 ouid=0


There's one particular entry, where when I select it it says, the package providing libinput-gestures could not be found, if you want to generate a stack trace please re-install it.

https://github.com/bulletmark/libinput-gestures - this is the program, it doesn't have an associated deb package.

If after that I click on anything in the reports window, the program crashes.
