### ISSUE TITLE
Check Root Status for root-password-not-set

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintreport#32]
Hi,

Checking Root account's warning always show on Mintreport's new version unless we ignore it. If the root account is enabled, can you hide this warning automatically? Following command's output shows root account's status.

`sudo passwd -S root | awk '{print $2}'`

If the output is L, root account is locked. If the output is P, root account is active.

**Comment by clefebvre** [comment]
We don't have root access within the check.
