### ISSUE TITLE
Set the root password - not clear

### ISSUE THREAD

**Issue by rharolde** [linuxmint/mintreport#33]
According to issue #32, the status cannot be checked.  So that needs to be made clear in the description, and there should be a button like "I have set the password".  Otherwise users will be frustrated wondering why the error never goes away.  (And not wanting to ignore it.)

p.s. Should I have re-opened #32 instead?

**Comment by clefebvre** [comment]
This was fixed already. We put a button "I understand". You're not expected to set a password, you can decide not to. The report is there to make you aware of this, that's all.

**Comment by rharolde** [comment]
It still was not clear to me that there was no check being done.  I was still confused.  But this is not as significant as other issues, so I understand if you leave it.

**Comment by Salfa83** [comment]
I agree to rharolde. I was also wondering, why this message did not disapper, despite I had set a root password (several times!).
It would be much more useful, if the message only appears, if the root password is definitely not set.
