### ISSUE TITLE
Pinned updates are available 

### ISSUE THREAD

**Issue by demonbob** [linuxmint/mintreport#35]
Two machines, upgraded from 19.2 cinnamon are showing "Pinned updates are available" in mintreport. However, running apt-mark showhold on both machines returns no pinned updates. However it looks like mintreport is running off of code in mint-dev-tools (yes I have them installed) as that is the only referance to the string "Pinned updates are available" when searching github.

**Comment by mtwebster** [comment]
You can ignore them - they are indeed caused by having mint-dev-tools installed.  They're to let us know there are new packages upstream (that we may be pinning or modifying the packages for in Mint).

**Comment by claudiux** [comment]
This requires better explanations in mintreport.
