### ISSUE TITLE
cpu at 100% during operations

### ISSUE THREAD

**Issue by purplesrl** [linuxmint/mintreport#37]
Running on 19.3 xfce

On system checks CPU goes to 100%, but thats not the biggest issue, the biggest is that when I install language packs, drivers etc (I think when it opens a new window to do stuff), the CPU remains at 100% 

I experienced this on 2 computers:

1. Fresh install
2. Upgrade to 19.3

**Comment by prateekamana** [comment]
This happened to me on linux mint 20 beta, a process called mintreport was running in background which was causing it. Was that your case too ?

**Comment by purplesrl** [comment]
yes, it happens when it calls another process

**Comment by prateekamana** [comment]
That happened even in mint 20 beta, I have just opened an issue

**Comment by prateekamana** [comment]
https://github.com/linuxmint/mint20-beta/issues/151

**Comment by spicysomtam** [comment]
Happened to me. Mint 19.3 cinnamon. Made a change from Google Chrome :)

**Comment by ronohara** [comment]
Still happening in Mint 20.1

**Comment by mmortal03** [comment]
I'm seeing this in 20.3 in a Linux Mint VirtualBox instance. mintreport cpu usage spikes to 100% as soon as it asks me to authenticate to install multimedia codecs, but I can carefully type the password (starts to get double keystroke inputs), but then the installation process hangs installing packages at post installation trigger dpkg-exec.
