### ISSUE TITLE
Unclear "problem" for "Intel Corporation Wireless 8260"   left without any UI option

### ISSUE THREAD

**Issue by bentolor** [linuxmint/mintreport#43]
Mint Report raised my attention but left me puzzled about what it actually wants. I let screenshots speak, here only the basic cornerpoints

- My Wifi has worked ever since
- On following the steps I cannot chose any option other than "manual driver". Even then I cannot choose any button
- Am I supposed to install the proposed backport-driver?
- What's the trigger?
- Find below my `lspci` output

![Screenshot from 2020-01-15 10-34-25](https://user-images.githubusercontent.com/588260/72422744-44a30800-3783-11ea-9f03-6ad9eafa20d5.png)

![Screenshot from 2020-01-15 10-35-10](https://user-images.githubusercontent.com/588260/72422752-48cf2580-3783-11ea-84d3-a4737cca8371.png)

![Screenshot from 2020-01-15 10-35-45](https://user-images.githubusercontent.com/588260/72422757-4a98e900-3783-11ea-8cb8-0db0d8d6fe33.png)

```
$ lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.2 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #3 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection I219-LM (rev 21)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
04:00.0 Network controller: Intel Corporation Wireless 8260 (rev 3a)
```

**Comment by bentolor** [comment]
Here what `ubuntu-driver` is saying

```
$ ubuntu-drivers list
backport-iwlwifi-dkms
$ ubuntu-drivers devices
== /sys/devices/pci0000:00/0000:00:1c.2/0000:04:00.0 ==
modalias : pci:v00008086d000024F3sv00008086sd00001130bc02sc80i00
vendor   : Intel Corporation
model    : Wireless 8260
manual_install: True
driver   : backport-iwlwifi-dkms - distro free
```

**Comment by mtwebster** [comment]
Are you on Ubuntu?

**Comment by bentolor** [comment]
@mtwebster No – of course Linux Mint Tricia.

**Comment by dannn-o** [comment]
Issue has been posted with this forum thread as well : [https://forums.linuxmint.com/viewtopic.php?f=47&t=309650&p=1745182#p1745182](https://forums.linuxmint.com/viewtopic.php?f=47&t=309650)
Reports from one of the responders is that the mintreport update that was just released (1.1.6) will resolve the problem.

**Comment by mtwebster** [comment]
Yes, sorry I meant to mention that here - there is a mintdrivers update as well.

**Comment by bentolor** [comment]
Can confirm: https://github.com/linuxmint/mintreport/commit/c6d95f978e1208b71abfc165b5d5c3a1f94db638 in 1.16 hides all drivers marked for "manual install" and this message disapperars. 

Thanks for you support, guys! Closing this issue.
