### ISSUE TITLE
Feature: Provide a button to delete old crash reports

### ISSUE THREAD

**Issue by jtsagata** [linuxmint/mintreport#44]
Provide a button to delete old crash reports, to gain some space. 

The local files button is misleading, as it doesn't show the location of crash data. Maybe add a button "delete report" bellow it, and a button or menu option to delete all crash reports?

**Comment by jefferystone** [comment]
The crash files are located under:  /var/lib/systemd/coredump

you will need root permissoin to remove these

**Comment by LinuxOnTheDesktop** [comment]
It seems to me that at the least there ought to be an option to remove old crash reports. One should not have to create a cron job to do it.

**Comment by mtwebster** [comment]
The actual core files are removed after 2 weeks by default, handled by the systemd-tmpfiles service.

This is defined in `/usr/lib/tmpfiles.d/systemd.conf`:
```
d /var/lib/systemd/coredump 0755 root root 2w
```

If you want to change this you could create a file of the same name in `/etc/tmpfiles.d`, and add just that line, modified to whatever limit you'd like.  There are ways to specify a maximum amount of disk space used as well. By default it's up to 10% of your disk size.

You can observe that coredump files are deleted after some time by running `coredumpctl`. It will always show all coredump entries as far back as the journal goes, but only the most recent ones have files (which are all that show up in mint-reports).

I think a button is overkill in this instance.
