### ISSUE TITLE
[Feature Request] Notify the user for updated Cinnamon extesnsions/applets/desklets/themes

### ISSUE THREAD

**Issue by NZamp** [linuxmint/mintreport#45]
Currently there is no notification in Cinnamon that some extension (or applet, desklet, theme) has an updated version available.

The only way that the user can be notified for such updates is by installing applets like spices-update, or manually check each settings module for applets, desklets, extensions or themes, which is not optimal.

It would be handy if mintreport is used to notify Cinnamon users for updates in their extensions etc, that they have already installed. 

Actually, it would be more cohesive if this feature could be implemented in mintupdate, but I'm not sure that it can be done as mintupdate is specific to apt updates.

**Comment by mtwebster** [comment]
This is handled in mintupdate now.
