### ISSUE TITLE
Main Menu Icon descriptions are overwriting each other

### ISSUE THREAD

**Issue by ol69stang** [linuxmint/mintreport#52]
End User here, not a programmer. (Please be kind).  Just recently pushed through all kinds of updates and now the main menu icons' descriptions are overwriting each other making the words unreadable.  When I scroll the highlight each icon by hovering, they clear up until I hover over another menu section.  Not sure why this happened.  
![Screenshot from 2020-05-19 13-13-05](https://user-images.githubusercontent.com/65625979/82373563-975f2b80-99d2-11ea-8485-d7a05f7134a1.png)
![Screenshot from 2020-05-19 13-14-46](https://user-images.githubusercontent.com/65625979/82373677-c4134300-99d2-11ea-9364-f34412dbda0c.png)

System info:
![Screenshot from 2020-05-19 13-17-35](https://user-images.githubusercontent.com/65625979/82373902-279d7080-99d3-11ea-9ca0-a07fd85b19aa.png)

Thank you all.

**Comment by JosephMcc** [comment]
Thanks for the report but this is a Cinnamon issue. If you are still experiencing it could you open a report here if there isn't already one: https://github.com/linuxmint/cinnamon/issues
