### ISSUE TITLE
"Ignore this report" button translation issue

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintreport#58]
Distro: Linux Mint 20
Mintreport: 1.2.1

Hi,

"Ignore this report" button translations can't get from locales files.  

![mintreport-fr](https://user-images.githubusercontent.com/1300133/90957299-537a3780-e495-11ea-8c71-8138760a0729.png)

![mintreport-de](https://user-images.githubusercontent.com/1300133/90957300-56752800-e495-11ea-9951-e1b38634cbc0.png)

![mintreport-tr](https://user-images.githubusercontent.com/1300133/90957302-58d78200-e495-11ea-88de-d90613ce4e2f.png)

**Comment by mtwebster** [comment]
fixed by https://github.com/linuxmint/mintcommon/pull/42
