### ISSUE TITLE
Ability to report bugs like `$ ubuntu-bug <package name>`

### ISSUE THREAD

**Issue by orschiro** [linuxmint/mintreport#6]
Dear all, 

Are there any plans to provide a bug reporting system similar to `$ ubuntu-bug <package name>`?

I just tried it with an example package (`$ mintreport mps-youtube`) but it wasn't clear to me how to get this report to Launchpad. 

Thanks for your comments!

**Comment by clefebvre** [comment]
Feature not planned.
