### ISSUE TITLE
View mode changes when opening folder as root (Nemo)

### ISSUE THREAD

**Issue by raulsas** [linuxmint/mintreport#61]
The icon view seems to be set as default when opening as root (right click on any folder & open as root)
I expected to keep the configuration of the non-root window.

Linux mint 19.3 , Nemo 4.4.3

**Comment by JosephMcc** [comment]
This seems to be an issue about Nemo. Please open a report here: https://github.com/linuxmint/nemo/issues if one does not already exist.
