### ISSUE TITLE
Mint Report reports update available for Chromium when it is not

### ISSUE THREAD

**Issue by vimes666** [linuxmint/mintreport#64]
Hi, Mint reports gives me a message that there is a new version of Chromium available, however not according to the update-manager.
I posted this problem on the mint forum here https://forums.linuxmint.com/viewtopic.php?p=1931483#p1931483 and was advised to ask Clem :)
This happens on only one of my 3 LMDE4 pc's. I did some comparing and I found that the misbehaving install had an extra folder called /usr/share/linuxmint/mintreport/reports/655-upstream-chromium containing the script MintReportInfo.py that is resposible for the message I am getting.
When I checked its date I noticed that it got there on the same date as I installed mint-dev-tools. And that pc is also the only LMDE pc where I installed it.
Now I noticed also that this script is not present in the github source so I am a bit confused now.
I have set this specific mint report to ignore for the time being but I would like to understand this.

**Comment by mtwebster** [comment]
This is indeed part of mint-dev-tools (it's sort of a report 'plugin' for mint-report). It's for our use to give a reminder when to get the next release of chromium ready. You can go ahead and permanently ignore it if you wish.

Maybe I'll put something on it to flag it as "internal use only".

https://github.com/linuxmint/mint-dev-tools/tree/master/usr/share/linuxmint/mintreport/reports/655-upstream-chromium
