### ISSUE TITLE
[Feature Request] detect laptop, if true suggest install tlp

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintreport#66]
Hi,

Could you add tlp installation suggestion for laptops to mintreport?

https://linrunner.de/tlp/

**Comment by MidnightNerd** [comment]
This is a good idea, as it really improves battery life. (I've seen 2 times longer usage on battery)
In my opinion linux mint should ask for that  when it's installed. 
I guess the best would be to have the tlp features directly integrated into the operating system but this is somehow some work to do.
