### ISSUE TITLE
[Bug?] applications listed multiple times at "all applications"

### ISSUE THREAD

**Issue by AdiWeit** [linuxmint/mintreport#78]
I don't know if it is a bug or intentional, but when I manually add an application to multiple categories in the menu, it will be listed as often as I added it at "all applications". It even happens with the "Recent places" and favorites.
Even if it is intentional I think for a better overview it would be great to list it just once.
I am using Linux Mint Version 20.1, so maybe it is fixed already, but I didn't recognize it in the release notes I read.

**Comment by clefebvre** [comment]
This isn't related to mintreport.
