### ISSUE TITLE
It might be an idea were the MintReport UI to appear when the startup item is run manually

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintreport#80]
What happens:

- open Startup Applications;
- select 'System Reports';
- click the 'run now icon';
- nothing perceivable happens, but in fact mintreport-tray runs.

What I expect: 

- the Mint Report GUI to appear;
- also, is mintreport-tray supposed to show something in the system tray? It doesn't do so on my system (or at least not on one of my Mint PCs; I should check my other Mint PC).

I realise that the user who investigates the startup item will see that it is mintreport-tray. But, still, the startup entry is labelled, 'Troubleshoot problems', which will encourage users to click on it.

Also: at present I don't run have the autorun enabled. Is this why, when I run mintReport manually, it never shows any dumps?

**Comment by clefebvre** [comment]
It only shows something if it finds an issue.

If it's not enabled in the Startup Apps it just doesn't check.

I don't think it's a bug, this does what it's supposed to do. I'd argue the confusion is more on the Cinnamon side of things, this tool shouldn't really be messed up with.
