### ISSUE TITLE
Multiple "Mint EOL" reports

### ISSUE THREAD

**Issue by jjg-dressipi** [linuxmint/mintreport#86]
Starting today, I get warnings "your version of linux mint will soon reach end of life EOL", useful information for sure, but repeated every hour.  Soon I will learn that "new reports" in the system tray is to be expected and ignore it, then when something else goes wrong I will not find out, reducing the utility of the tool.

**Comment by clefebvre** [comment]
Can you provide a screenshot and your version of Linux Mint?

**Comment by clefebvre** [comment]
I get your point @jjg-dressipi, and I agree with the notion that constant nagging results in the user paying less and less attention.

This is a special case though, it requires an action, the OS is becoming useless without an upgrade. The lack of ignore button is by design in this report.

**Comment by nzbtuxnews** [comment]
I concur with the OP, this is annoying.  I know my Mint version is EOL but I cannot migrate now and need to move stuff and reorganize my data before I wipe this computer clean and reinstall a new version.  There should be a button to "mute" this alert, or ignore it completely.  After all, this is a personal decision to move to a newer version or not (not that I encourage people to stay on obsoleted versions of anything)...

> it requires an action, the OS is becoming useless without an upgrade

What do you mean by "useless"?  Will it stop functioning the next day or will it self destruct?  Some people are still running windows 7 knowing willfully it is very obsolete.  Look at the pushback with win10.

Overall, I dislike this kind of software behavior.  OK to warn and have emphasis on something serious, but its another thing to FORCE something when really it doesnt have to.  This is a very concerning trend in software development nowadays, and we can see it in windows as well as more and more in the open source world...

My 2 cents.
