### ISSUE TITLE
[Idea] - Add option to install Flatpak themes

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mintreport#88]
By default flatpak themes are not installed [as I understand mintupdate checks the current theme and downloads the corresponding one when installing an app in this format].   People using flatpaks may have problems with the interface of the apps [window borders, colors, etc] as switching accents or to a dark theme usually breaks the theme of the apps.

Maybe mintreport can show a message in 'system reports' that allows to install  flatpak themes [as it happens when language packages are missing].

They don't [weigh much](https://github.com/orgs/flathub/repositories?language=&page=1&q=org.gtk.Gtk3theme.Mint&sort=&type=all)

**Comment by mtwebster** [comment]
There were already multiple places that new themes get installed if necessary -

It happens:
- Any time a new flatpak is installed via Mintinstall.
- By mintupdate when installing updates

It was also getting done during automatic flatpak updates, but I've just changed that so it occurs at startup even if updates are disabled: https://github.com/linuxmint/mintupdate/commit/bc290709bc0dcbf8cf9b81fee56f58db24d9dba1

With all of that in place, I don't think this issue rises to the level of needing to bother the user about it also.
